"""
EmailAgent — Phase 1

Responsibility:
  Sends an email summary after a GitHub issue is created.

Input context keys:
  - title: str
  - description: str
  - deadline: str | None
  - priority: str
  - github_issue_url: str
"""
from backend.agents.base_agent import BaseAgent, AgentResult
from backend.services.mailer_service import MailerService
from backend.core.logging import get_logger

logger = get_logger(__name__)


class EmailAgent(BaseAgent):
    name = "EmailAgent"

    def __init__(self):
        self.mailer = MailerService()

    async def run(self, context: dict) -> AgentResult:
        title = context.get("title", "Task")
        description = context.get("description", "")
        deadline = context.get("deadline", "Not specified")
        priority = context.get("priority", "MEDIUM")
        github_url = context.get("github_issue_url", "")

        subject = f"[AI Task Created] {title}"
        body = self._build_email_body(title, description, deadline, priority, github_url)

        logger.info(f"[{self.name}] Sending email: {subject!r}")
        try:
            await self.mailer.send(subject=subject, body=body)
        except Exception as e:
            return AgentResult(success=False, error=str(e))

        logger.info(f"[{self.name}] Email sent successfully")
        return AgentResult(
            success=True,
            output={"email_sent": True, "subject": subject},
        )

    def _build_email_body(self, title, description, deadline, priority, github_url) -> str:
        return f"""
<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h2 style="color: #1a73e8;">🤖 AI Orchestrator — New Task Created</h2>
  <hr/>

  <h3>{title}</h3>

  <table style="width:100%; border-collapse: collapse;">
    <tr>
      <td style="padding: 8px; background:#f1f3f4; font-weight:bold; width:30%;">Priority</td>
      <td style="padding: 8px;">{priority}</td>
    </tr>
    <tr>
      <td style="padding: 8px; background:#f1f3f4; font-weight:bold;">Deadline</td>
      <td style="padding: 8px;">{deadline or "Not specified"}</td>
    </tr>
  </table>

  <h4>Description</h4>
  <p>{description or "No description provided."}</p>

  {"<h4>GitHub Issue</h4><p><a href='" + github_url + "'>" + github_url + "</a></p>" if github_url else ""}

  <hr/>
  <small style="color:#888;">This email was automatically generated by AI Orchestrator.</small>
</body>
</html>
"""
